name: realestate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.41+41

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  syncfusion_flutter_gauges: ^30.1.39
  firebase_messaging: ^15.2.9
  cached_network_image: ^3.4.1
#  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  secure_content: ^1.0.1
  flutter_portal: ^1.1.4
#  firebase_app_check: ^0.3.2+9
  razorpay_flutter: ^1.4.0
  dio: ^5.8.0+1
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  webview_flutter: ^4.13.0
  syncfusion_flutter_pdfviewer: ^30.1.39
  flutter_html: ^3.0.0
  printing: ^5.14.2
  percent_indicator: ^4.2.5
  fl_chart: ^1.0.0
  youtube_player_flutter: ^9.1.1
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  flutter_spinkit: ^5.2.1
  flutter_dash: ^1.0.0
  number_to_words_english: ^2.1.1
  upgrader: ^11.4.0
  flutter_local_notifications: ^19.3.0
  flutter_rating_bar: ^4.0.1
#  cloud_firestore: ^5.6.11
  font_awesome_flutter: ^10.8.0
  searchable_paginated_dropdown: ^1.3.0
  animate_do: ^4.2.0
  dropdown_button2: ^2.3.9
  uuid: ^4.5.1
  pin_code_fields: ^8.0.1

  better_player_plus: ^1.1.5
  wakelock_plus: ^1.4.0
  share_plus: ^12.0.1
  new_version_plus: ^0.1.1
  package_info_plus: ^9.0.0












dependency_overrides:
  win32: ^5.0.2
  audioplayers: ^5.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_icons:
    android: true
    image_path: "assets/sk_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/



